export const PROMPTS = {
  highMoodHighCompletion: [
    "You're operating well. Write the recipe: what exact conditions (sleep, schedule, environment, mindset) created this week?",
    "Describe the internal state you're in right now — not what you *did*, but what it *feels* like to be in momentum.",
    "What version of yourself is now possible that wasn't two months ago? Be specific.",
    "Who deserves to hear 'you made a difference in this'? What would you say to them?",
    "What are you taking for granted right now that you should consciously appreciate before it changes?",
    "What would you do differently if you knew this window of clarity was temporary?",
  ],
  highMoodLowCompletion: [
    "You're feeling good even though the numbers are lower. What's sustaining your mood independent of your output?",
    "Name the one habit that, if done daily for 30 days, would change everything else. Start with that.",
    "What's the exact friction point between your current state and your target completion rate? Be surgical.",
  ],
  lowMoodHighCompletion: [
    "You're showing up even when it's hard. That *is* discipline — the definition of it. What's keeping you going?",
    "Your actions and feelings are disconnected: your actions are *ahead*. Trust the actions; feelings catch up.",
    "What is the feeling underneath the low mood? Give it the most precise name you can.",
    "What need — sleep, connection, rest, creative space — is going unmet right now?",
    "If you could change one thing about your environment this week, what would it be, specifically?",
  ],
  lowMoodLowCompletion: [
    "No performance pressure. Just write. What's actually going on right now?",
    "What's the smallest possible version of tomorrow that would feel like a win — genuinely, not aspirationally?",
    "Who in your life would you want to talk to right now? What would you tell them?",
    "What would it mean to be *kind* to yourself this week, concretely? Not vaguely — specifically.",
    "List three things that are working, no matter how small. Start with the most mundane.",
  ],
  goalFocused: [
    "Your most important goal: what's the one daily action that makes all other actions less important?",
    "Describe the day you hit this goal. Who are you with? Where are you? What does the moment feel like?",
    "What would you need to *believe* about yourself to pursue this goal confidently?",
    "What are you using as an excuse that you could simply — honestly — stop using?",
    "If your goal could speak, what would it say to you right now?",
  ],
  streakProtect: [
    "You have a streak worth protecting. Write the contingency plan for your three hardest possible days.",
    "What is the absolute minimum version of each habit that still *counts*? Write these down now, not when you need them.",
    "Describe a day where everything goes wrong. Walk through exactly how you protect the streak anyway.",
    "Your streak is data: what does it tell you about who you are that you didn't know when you started?",
  ],
  weeklyReview: [
    "Rate this week 1–10 across: energy, focus, relationships, health, output. What drove each score?",
    "What one decision from this week would you undo? What would you do instead?",
    "What did you learn about yourself this week that you didn't know on Monday?",
    "Which habit showed up most reliably? What made it stick when others didn't?",
    "What gets consciously carried forward into next week, and what gets deliberately left behind?",
    "What surprised you this week? About yourself, or the world?",
  ],
  deepReflection: [
    "What fear is disguising itself as procrastination right now?",
    "Describe your ideal life in 5 years without referencing money, status, or achievements.",
    "What belief about yourself — formed before age 20 — needs updating?",
    "What are you most proud of that no one knows about?",
    "What would you do if you knew no one was watching or judging?",
    "Write a brief obituary of the version of you that gives up easily.",
    "What conversation are you avoiding that would free up the most mental energy?",
    "What does 'enough' actually look like for you? In work, in habits, in achievement?",
  ],
  morningIntent: [
    "One word for today. Why that word?",
    "What is the single thing that, if done today, makes everything else easier or irrelevant?",
    "Who do you want to be today? Describe it behaviourally — not 'be kind' but 'I will...'",
    "What are you most looking forward to today? Start there.",
    "What would today look like if it were 10% better than yesterday?",
  ],
  eveningClose: [
    "Three things that went well today, and *why* they went well. The why matters more than the what.",
    "One thing you'll do differently tomorrow. Not 'should' — *will*.",
    "Who did you genuinely help today, even in a small way?",
    "What part of today are you at peace with, even if it wasn't perfect?",
    "Rate your energy at end-of-day: what consumed it most? What created it?",
    "What did today teach you about your capacity?",
  ],
  scienceBased: [
    "Research shows self-compassion after setbacks predicts faster recovery than self-criticism (Neff, 2003). Where could you apply this concretely this week?",
    "The best predictor of future behaviour is past behaviour, not intentions. Looking at your last 14 days: what pattern are you reinforcing?",
    "Writing about goals for 15–20 minutes improves attainment by 42% (Pennebaker & Seagal, 1999). Use this session for exactly that — one specific goal, 15 minutes.",
  ],
  gratitude: [
    "Three people who made a positive difference in the last 7 days. What specifically did they do?",
    "What about your body are you grateful for today? Be specific — not 'my health' but what it let you *do*.",
    "What challenge are you secretly grateful for, because of what it's building in you?",
    "Describe one moment from today, however small, that was genuinely good.",
  ],
};
